const status = {
  HTTP_OK_STATUS: 200,
  NOT_FOUND_STATUS: 404,
  UNAUTHORIZED_STATUS: 401,
  INTERNAL_SERVER_ERROR: 500,
  INCORRECT_REQUEST: 400,
  CREATED_STATUS: 201,
  NO_CONTENT_STATUS: 204,
};

module.exports = status;
